library(renv)

renv::init()
renv::install("tidyverse")
renv::install("dbplyr")
renv::install("duckdb")
renv::install("DBI")
renv::install("fs")
renv::install("vroom")
renv::install("bioc::GenomicRanges")
renv::install("bioc::AnnotationHub")
renv::install("furrr")
renv::snapshot()
